### ISSUE TITLE
请求适配知乎5.41.0

### ISSUE THREAD

**Issue by BaileyZyp** [picone/ZhihuXposed#5]
希望作者适配一下新版 谢谢
知乎开屏广告是否有可能去除

**Comment by picone** [comment]
知乎每次发新版混淆的都会变，建议找到能用的版本就别更新了。开屏广告有点头疼，还没找到哪里弹出来的。

**Comment by iaston** [comment]
知乎可以过滤广告粉老版本不能用了

**Comment by kotori2** [comment]
@picone 刚才拆了一下最新的APK(6.10.0)，把几个混淆变了的HOOK点改了一下
```
public final static String CLASS_JSON_PARSER = "com.fasterxml.jackson.b.j"; //com.fasterxml.jackson.core.JsonParser
public final static String CLASS_JSON_DESERIALIZATION_CONTEXT = "com.fasterxml.jackson.databind.g";//DeserializationContext
public final static String CLASS_ZH_OBJECT_DESERIALIZER = "com.zhihu.android.app.base.utils.ZHObjectDeserializer";
```
发现feed的hook和答案下方广告hook均已失效
@xfl03 不知道有没有空来玩（

**Comment by kotori2** [comment]
好的 我研究了一下，发现现在知乎已经把整个回答页面做成webview了
![image](https://user-images.githubusercontent.com/17663689/63776415-f3999100-c913-11e9-88bf-688165e3c42d.png)
然后我就在撕烤 能不能执行js脚本把广告去掉，于是我Hook了`com.zhihu.android.answer.module.content.appview.AnswerAppView`的`onWebPageReady`方法
```
XposedHelpers.callMethod(param.thisObject, "evaluateJavascript", "document.getElementsByClassName(\"AnswerFooter\")[0].innerText += \" Xposed已生效\";", new ValueCallback<String>() {
    @Override
    public void onReceiveValue(String s) {
        XposedBridge.log(s);
    }
});
```
结果代码是执行了，logcat也能抓到返回值
```
EdXposed-Bridge: "编辑于 2019-06-20・著作权归作者所有 Xposed已生效"
```
但是实际上页面没有变？

**Comment by kotori2** [comment]
试了一圈，找到了两个有用的注入点
1. `setContentPaddingTop`，这里官方就执行了一条js设置padding，但是缺点是`evaluateJavascript`这个函数一次只能执行一条命令，而且是在页面加载完成以后（？）执行，用起来比较难受
2. `processHtmlContent` 这个函数参数包含HTML body，从这插代码还是比较合适的
待会发pr

**Comment by picone** [comment]
抱歉最近比较忙。
之前去掉答案页面广告的思路，是发现了广告是异步加载的，拦截其异步加载的请求并修改起回包为空，骗他不用加载广告

**Comment by kotori2** [comment]
@picone #8

**Comment by picone** [comment]
> @picone 刚才拆了一下最新的APK(6.10.0)，把几个混淆变了的HOOK点改了一下
> 
> ```
> public final static String CLASS_JSON_PARSER = "com.fasterxml.jackson.b.j"; //com.fasterxml.jackson.core.JsonParser
> public final static String CLASS_JSON_DESERIALIZATION_CONTEXT = "com.fasterxml.jackson.databind.g";//DeserializationContext
> public final static String CLASS_ZH_OBJECT_DESERIALIZER = "com.zhihu.android.app.base.utils.ZHObjectDeserializer";
> ```
> 
> 发现feed的hook和答案下方广告hook均已失效
> @xfl03 不知道有没有空来玩（

似乎大部分json解析改成JNI方式解析```ZHObject```了，改成Register之前hook就行了，晚点commit
